### ISSUE TITLE
How would I integrate with oauth login

### ISSUE THREAD

**Issue by jokokucing** [trafficinc/CodeIgniter-Authit#1]
I would like to register a user who logs in with Facebook and updates the database each time they login if facebook data is updated.

Any suggestions?

**Comment by trafficinc** [comment]
I don't believe this is an issue as the basic functionality of the authentication library doesn't provide this.  I think you may be looking for a Open Auth solution where your user can sign into your app via Facebook/Open Auth, this library doesn't offer that functionality as of yet.

**Comment by jokokucing** [comment]
Yea I am sorry I didn't know where else to ask.
