### ISSUE TITLE
Last login error

### ISSUE THREAD

**Issue by rodrigoarreola** [trafficinc/CodeIgniter-Authit#2]
I'm getting a data base error when I try to create a new user because it says that the last_login variable is null but shouldn't be

**Comment by trafficinc** [comment]
I am wondering if this has to do with, in "models/Authit_model.php" you should add the last_login key (line 54):  
	public function create_user($email, $password)
	{
		$data = array(
			'email' => filter_var($email, FILTER_SANITIZE_EMAIL),
			'password' => $password, // Should be hashed
			'created' => date('Y-m-d H:i:s'),
                        **'last_login' => date('Y-m-d H:i:s')**
		);
		$this->db->insert($this->users_table, $data);
		return $this->db->insert_id();
	}

Can you let me know if this works? and I will update.

**Comment by rodrigoarreola** [comment]
Yeah, was that now works like a charm.

Thank you.

**Comment by trafficinc** [comment]
No problem, thanks
